### ISSUE TITLE
Google OAuth / Embedded WebView?

### ISSUE THREAD

**Issue by scgough** [Spicy-Sparks/react-native-google-one-tap-signin#10]
I have received a message from Google stating that part of the Google Auth flow (which uses this package) is potentially using a WebView. 
Has anyone else received this warning? I'm wondering if the issue is actually part of the `com.google.android.gms:play-services-auth` dependency. 
There is a fairly strict time limit (May 2023) to resolve the issue before users start receiving the `disallowed_useragent` warning.

**Comment by geroale** [comment]
@scgough Hello, have you found anything new about this issue? We didn't get this warning.

**Comment by scgough** [comment]
Nothing more since so I think 🤞🏻 its safe to say there’s no webview lurking anywhere 🙂

**Comment by geroale** [comment]
@scgough Alright, thank you 👍🏻
