### ISSUE TITLE
App crashed with error Given string is empty of null

### ISSUE THREAD

**Issue by tushargoyalofficial** [Spicy-Sparks/react-native-google-one-tap-signin#11]
Followed the steps mentions in docs. Just remove webclientid from configure and using like this. As I don't want gdrive or anything, just want google login

`import {
  GoogleOneTapSignIn,
  statusCodes,
} from 'react-native-google-one-tap-signin';

GoogleOneTapSignIn.configure();
`

`    try {
      await GoogleOneTapSignIn.hasPlayServices();
      const userInfo: any = await GoogleOneTapSignIn.signIn();
      setUserInf(userInfo);
      navigation.navigate('Home');
    } catch (error: any) {
      if (error.code === statusCodes.SIGN_IN_CANCELLED) {
        console.log(error.message);
      } else if (error.code === statusCodes.IN_PROGRESS) {
        console.log(error.message);
      } else {
        console.log(error.message);
      }
    }
`

**Comment by geroale** [comment]
@tushargoyalofficial Hello, I think the clientId is requested to make the login work. The documentation may be misleading in this case.
