### ISSUE TITLE
Missing serverAuthCode

### ISSUE THREAD

**Issue by mujehoxe** [Spicy-Sparks/react-native-google-one-tap-signin#13]
When offline access is enabled the response should contain a serverAuthCode

```
GoogleOneTapSignIn.configure({
      webClientId: WEB_CLIENT_ID,
      offlineAccess: true,
    });
const userInfo = await GoogleOneTapSignIn.signIn();
```

**Comment by mujehoxe** [comment]
This seems to be only possible using GoogleSignInAccount which doesn't have the password field, meaning the whole password use case should be removed (savePassword ...)
This is also reasonable, the application shouln't have access to the password, the password should only be known by the user don't you think?

**Comment by mujehoxe** [comment]
After further investigation with the docs, it seems impossible in order to get the auth code you need display a consent screen, and with one tap you can't. This is also true for scopes.

**Comment by geroale** [comment]
@mujehoxe Hello, to my understanding, serverAuthCode cannot be used. Regarding the savePassword method, that is a legacy method from the previous owner of this library, but it's not required to use it for the sign-in.
