### ISSUE TITLE
Missing the scopes attribute from the response

### ISSUE THREAD

**Issue by mujehoxe** [Spicy-Sparks/react-native-google-one-tap-signin#14]

**Comment by geroale** [comment]
@mujehoxe Hello, thank you for the report. Why do you need the scopes from the response? They should be the same ones you are requesting.

**Comment by mujehoxe** [comment]
Well, let's say i am used to it being in the response while using the google-sign package

**Comment by geroale** [comment]
@mujehoxe If it's possible to retrieve them from the SignInClient, a PR would be welcome to implement them :)

**Comment by mujehoxe** [comment]
From what i read it is not possible, scopes require consent screen
