### ISSUE TITLE
await GoogleOneTapSignIn.signIn() returns true instead of the user

### ISSUE THREAD

**Issue by arjendevos** [Spicy-Sparks/react-native-google-one-tap-signin#5]
```ts
return new Promise(async (resolve, reject) => {
    try {
      await GoogleOneTapSignIn.hasPlayServices();
      const userInfo = await GoogleOneTapSignIn.signIn();
      resolve(userInfo);
    } catch (error: any) {
      reject(error.code);
    }
  });
```

This returns `{user: true}`

**Comment by arjendevos** [comment]
Probably because i forgot `GoogleOneTapSignIn.configure();` but i can't test it because the configure function can't be run.

`TypeError: null is not an object (evaluating 'RNGoogleOneTapSignIn.configure')`

**Comment by geroale** [comment]
This package is meant only for Android only. If you are using it on iOS, we suggest avoiding calling its methods.
